packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@capacitor/android@8.5.1'
  - '@capacitor/cli@8.5.1'
  - '@capacitor/core@8.5.1'
